# Generated by Django 4.0.1 on 2022-03-26 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('number_class', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('fees', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Groups_students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('id_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon.group')),
            ],
        ),
        migrations.CreateModel(
            name='Groups_teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_teacher', models.CharField(default='one', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('id_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon.group')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_pic', models.ImageField(upload_to='media/student_pic')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('idcard', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=50)),
                ('phone_one', models.CharField(max_length=50)),
                ('phone_tow', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=50)),
                ('phone_one', models.CharField(max_length=50)),
                ('phone_tow', models.CharField(max_length=50)),
                ('degree_edu', models.CharField(max_length=50)),
                ('address_one', models.CharField(max_length=50)),
                ('address_tow', models.CharField(max_length=50)),
                ('idcord', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('final_score', models.PositiveIntegerField()),
                ('activate', models.PositiveIntegerField()),
                ('home_work', models.PositiveIntegerField()),
                ('group_student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='amazon.groups_students')),
            ],
        ),
        migrations.CreateModel(
            name='Present',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('group_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon.groups_students')),
            ],
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.PositiveIntegerField()),
                ('baqiyat', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('group_teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='amazon.groups_teachers')),
            ],
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datils', models.TextField()),
                ('money', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Middle_skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading', models.PositiveIntegerField(default=0)),
                ('writing', models.PositiveIntegerField(default=0)),
                ('listening', models.PositiveIntegerField(default=0)),
                ('speaking', models.PositiveIntegerField(default=0)),
                ('group_student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='amazon.groups_students')),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datils', models.CharField(max_length=150)),
                ('money', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='groups_teachers',
            name='id_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_one', to='amazon.teacher'),
        ),
        migrations.AddField(
            model_name='groups_students',
            name='id_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon.student'),
        ),
        migrations.CreateModel(
            name='Final_skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading', models.PositiveIntegerField(default=0)),
                ('writing', models.PositiveIntegerField(default=0)),
                ('listening', models.PositiveIntegerField(default=0)),
                ('speaking', models.PositiveIntegerField(default=0)),
                ('group_student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='amazon.groups_students')),
            ],
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees', models.PositiveIntegerField()),
                ('descount', models.PositiveIntegerField()),
                ('baqi', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('group_student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='amazon.groups_students')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('fees', models.PositiveIntegerField()),
                ('level', models.CharField(max_length=50)),
                ('phone_one', models.CharField(max_length=50)),
                ('phone_tow', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[(1, 'student_school'), (2, 'graduate_school'), (3, 'student_university'), (4, 'graduate_university')], max_length=150)),
                ('form', models.CharField(max_length=150)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='amazon.student')),
            ],
        ),
        migrations.CreateModel(
            name='Amount_salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_salary', models.CharField(max_length=50)),
                ('salary', models.PositiveIntegerField()),
                ('group_teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='amazon.groups_teachers')),
            ],
        ),
        migrations.CreateModel(
            name='Address_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_one', models.CharField(max_length=150)),
                ('village_one', models.CharField(max_length=150)),
                ('province_tow', models.CharField(max_length=150)),
                ('village_tow', models.CharField(max_length=150)),
                ('new_address', models.TextField()),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='amazon.student')),
            ],
        ),
    ]
