# Generated by Django 4.0.1 on 2022-03-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0002_group_groups_students_groups_teachers_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='active',
            field=models.CharField(default=1, max_length=8),
        ),
    ]
