# Generated by Django 4.0.1 on 2022-03-29 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0004_alter_customuser_user_type_oner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'Admin'), (2, 'HOD'), (4, 'Teacher')], default=2, max_length=50),
        ),
    ]
