# Generated by Django 4.0.1 on 2022-03-29 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0005_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Oner',
            new_name='Staff',
        ),
    ]
