# Generated by Django 4.0.1 on 2022-04-02 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0009_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='group_student',
        ),
        migrations.AddField(
            model_name='attendance',
            name='group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='amazon.group'),
            preserve_default=False,
        ),
    ]
