# Generated by Django 4.0.1 on 2022-04-20 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0011_delete_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Count_salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_salary', models.CharField(max_length=50)),
                ('salary', models.PositiveIntegerField()),
                ('group_teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='amazon.groups_teachers')),
            ],
        ),
    ]
