# Generated by Django 4.0.1 on 2022-04-26 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0017_total_salary_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='total_salary',
            name='by',
        ),
    ]
