# Generated by Django 4.0.1 on 2022-04-26 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0018_remove_total_salary_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='total_salary',
            name='by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
