# Generated by Django 4.0.1 on 2022-04-28 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0019_total_salary_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups_teachers',
            name='include',
            field=models.CharField(default='one', max_length=5),
        ),
        migrations.AlterField(
            model_name='groups_teachers',
            name='position_teacher',
            field=models.CharField(default='one', max_length=5),
        ),
    ]
