# Generated by Django 4.0.1 on 2022-04-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0021_teacher_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='amount_salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='amount_salary',
            field=models.IntegerField(default=0),
        ),
    ]
