# Generated by Django 4.0.1 on 2022-04-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0022_staff_amount_salary_teacher_amount_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='baqiyat',
        ),
        migrations.AddField(
            model_name='pay',
            name='active',
            field=models.CharField(default=1, max_length=3),
        ),
    ]
