# Generated by Django 4.0.1 on 2022-05-08 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0023_remove_pay_baqiyat_pay_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acount_stu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('datils', models.TextField()),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='amazon.student')),
            ],
        ),
    ]
