# Generated by Django 4.0.4 on 2022-05-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0027_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
